export const StudentData = [
  {
    id: 1,
    name: "Tausif Ahmed",
    scores: "A+",
    percentage: "90%",
    class: "one",
  },
  {
    id: 2,
    name: "Yeasin Ahmed",
    scores: "A+",
    percentage: "90%",
    class: "one",
  },
  {
    id: 3,
    name: "Kawsar Ahmed",
    scores: "F",
    percentage: "90%",
    class: "one",
  },
  {
    id: 4,
    name: "Imam Hossain",
    scores: "F",
    percentage: "90%",
    class: "one",
  },
  {
    id: 5,
    name: "Monwar Hossain",
    scores: "B",
    percentage: "40%",
    class: "one",
  },
  {
    id: 6,
    name: "Sayed Ahmed",
    scores: "D",
    percentage: "30%",
    class: "one",
  },
  {
    id: 7,
    name: "Akidul Islam",
    scores: "A+",
    percentage: "98%",
    class: "one",
  },
  {
    id: 8,
    name: "Freelancer Riad",
    scores: "F",
    percentage: "90%",
    class: "one",
  },
  {
    id: 9,
    name: "Shuvo Mia",
    scores: "C",
    percentage: "45%",
    class: "one",
  },
  {
    id: 10,
    name: "Sumit Saha",
    scores: "F",
    percentage: "10%",
    class: "one",
  },
  {
    id: 11,
    name: "Tufazzol Ahmed",
    scores: "A+",
    percentage: "90%",
    class: "two",
  },
  {
    id: 12,
    name: "Shuvo Dev",
    scores: "A+",
    percentage: "90%",
    class: "two",
  },
  {
    id: 13,
    name: "Dipto Hossain",
    scores: "A",
    percentage: "75%",
    class: "two",
  },
  {
    id: 14,
    name: "Ali Hossain",
    scores: "F",
    percentage: "10%",
    class: "two",
  },
  {
    id: 15,
    name: "Sojib Talukder",
    scores: "B",
    percentage: "40%",
    class: "two",
  },
  {
    id: 16,
    name: "Sayed Huzur",
    scores: "F",
    percentage: "7%",
    class: "two",
  },
  {
    id: 17,
    name: "Fullstck Akidul",
    scores: "D",
    percentage: "23%",
    class: "two",
  },
  {
    id: 18,
    name: "Backend Sayed",
    scores: "F",
    percentage: "05%",
    class: "two",
  },
  {
    id: 19,
    name: "Akash Ahmed",
    scores: "C+",
    percentage: "45%",
    class: "two",
  },
  {
    id: 20,
    name: "Mir Hussain",
    scores: "C+",
    percentage: "30%",
    class: "two",
  },
  {
    id: 21,
    name: "Tonmoy Parvez",
    scores: "A+",
    percentage: "10%",
    class: "two",
  },
  {
    id: 22,
    name: "Tapas Adhikari",
    scores: "F",
    percentage: "10%",
    class: "three",
  },
  {
    id: 23,
    name: "Mijan Mia",
    scores: "A+",
    percentage: "10%",
    class: "three",
  },
  {
    id: 24,
    name: "Shamim Ahmed",
    scores: "A+",
    percentage: "10%",
    class: "three",
  },
  {
    id: 25,
    name: "Tahmina Akter",
    scores: "A+",
    percentage: "100%",
    class: "three",
  },
  {
    id: 26,
    name: "Ruman Ahmed",
    scores: "A",
    percentage: "79%",
    class: "three",
  },
  {
    id: 27,
    name: "Oashim Ahmed",
    scores: "A+",
    percentage: "90%",
    class: "three",
  },
  {
    id: 28,
    name: "Junayed Ahmed",
    scores: "B",
    percentage: "30%",
    class: "three",
  },
  {
    id: 29,
    name: "Towkir Ahmed",
    scores: "C",
    percentage: "10%",
    class: "three",
  },
  {
    id: 30,
    name: "Nipa Akter",
    scores: "F",
    percentage: "10%",
    class: "three",
  },
];
